OBJ_FOLDER = "objects"
_OG_PLY_FILE_NAME = "HECTOR_2020-07-20-13-53-55-segmented_vineyard.ply"
_INLINE_PLY_FILE_NAME = "HECTOR_2020-07-20-13-53-55-segmented_vineyard-inliers.ply"
_SLICE01_PLY_FILE_NAME = "vineyard_inliers_PCA_slice-slice_dst=0.1.ply"
_SLICE01_INLIERS_K_20_DEV_3_PLY_FILE_NAME = "vineyard_inliers_PCA_slice-slice_dst=0.1_inliers-k=20-std_dev=3.ply"
_ABOVE_GROUND_06_PLY_FILE_NAME = "vineyard_inliers_above_ground-max_dst=0.6.ply"
_SMALL_VINEYARD_FILE_NAME = "Vinograd_mali-Cloud.ply"

OG = "OG"
INLIERS = "inliers"
SLICE_01 = "slice_dst=0.1"
SLICE_01_INLIERS_K_20_DEV_3 = "slice_dst=0.1-inliers_k=20_dev=3"
ABOVE_GROUND_06 = "above_ground-max_dst=0.6"
SMALL_VINEYARD = "small_vineyard"
